In [35]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
import sklearn

In [2]:
df=pd.read_csv(r"C:\Users\Prithweeraz\Desktop\Machine Leaning\মেশিন লার্নিং  ডিসিশন ট্রি  সাপোর্ট ভেক্টর মেশিন\2025-01-09T16-41-24.468Z-shop data.csv")

In [7]:
df.head()

age  income  gender m_status  buys
0    <25    high    male   single   Bad
1    <25    high    male  married   Bad
2  25-35    high    male   single  Good
3    >35  medium    male   single  Good
4    >35     low  female   single  Good

In [9]:
x=df.iloc[:,0:-1]

In [13]:
y=df.iloc[:,-4]

In [15]:
y

0       high
1       high
2       high
3     medium
4        low
5        low
6        low
7     medium
8        low
9     medium
10    medium
11    medium
12      high
13    medium
14      high
15      high
16    medium
17      high
18    medium
19      high
20    medium
21       low
Name: income, dtype: object

In [17]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le=LabelEncoder()

In [21]:
x=x.apply(le.fit_transform) 


In [23]:
x

age  income  gender  m_status
0     1       0       1         1
1     1       0       1         0
2     0       0       1         1
3     2       2       1         1
4     2       1       0         1
5     2       1       0         1
6     0       1       0         0
7     1       2       1         0
8     1       1       0         1
9     2       2       0         0
10    1       2       0         1
11    0       2       1         0
12    0       0       0         1
13    2       2       1         0
14    1       0       1         1
15    1       0       0         0
16    2       2       1         0
17    1       0       0         1
18    0       2       0         0
19    0       0       1         1
20    2       2       0         0
21    1       1       1         1

In [74]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=.3,random_state=1)

In [76]:
from sklearn.tree import DecisionTreeClassifier 
model=DecisionTreeClassifier()
model.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [78]:
model.predict(xtest)

array(['high', 'medium', 'medium', 'medium', 'medium', 'high', 'medium'],
      dtype=object)

In [80]:
model.score(xtest,ytest)

1.0

In [70]:
 cross_val_score 

In [82]:
result =cross_val_score(DecisionTreeClassifier(),x,y,cv=5)

In [84]:
result

array([1., 1., 1., 1., 1.])

In [88]:
result.mean()

1.0

In [104]:
from sklearn.linear_model import LogisticRegression
result =cross_val_score(LogisticRegression(),x,y,cv=5)
result

array([1.  , 1.  , 0.75, 1.  , 0.75])

In [102]:
result.mean()

0.9

In [108]:
from sklearn.preprocessing import MinMaxScaler
MMS=MinMaxScaler()
x_scaled= MMS.fit_transform(x)
x_scaled

array([[0.5, 0. , 1. , 1. ],
       [0.5, 0. , 1. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [0. , 0.5, 0. , 0. ],
       [0.5, 1. , 1. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 1. , 0. , 1. ],
       [0. , 1. , 1. , 0. ],
       [0. , 0. , 0. , 1. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 1. , 1. ],
       [0.5, 0. , 0. , 0. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 0. , 1. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 0.5, 1. , 1. ]])

In [114]:
from sklearn.neighbors import KNeighborsClassifier
result=result =cross_val_score(KNeighborsClassifier(),x,y,cv=5)

In [116]:
result

array([1.  , 1.  , 0.75, 1.  , 0.75])

In [118]:
result.mean()

0.9

In [136]:
aa=xtest.iloc[6:,:]

In [142]:
y_pred=model.predict(xtest)
y_pred

array(['high', 'medium', 'medium', 'medium', 'medium', 'high', 'medium'],
      dtype=object)

In [144]:
ytest

19      high
16    medium
3     medium
13    medium
18    medium
15      high
10    medium
Name: income, dtype: object

In [150]:
from sklearn.metrics import confusion_matrix

In [154]:
cm=confusion_matrix(ytest,y_pred)
cm

array([[2, 0],
       [0, 5]], dtype=int64)

In [174]:
from sklearn.metrics import classification_report

In [176]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

        high       1.00      1.00      1.00         2
      medium       1.00      1.00      1.00         5

    accuracy                           1.00         7
   macro avg       1.00      1.00      1.00         7
weighted avg       1.00      1.00      1.00         7

